CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE TYPE "UserRole" AS ENUM ('ADMIN','TEACHER','STUDENT');
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE','SUSPENDED','DELETED');
CREATE TYPE "Subject" AS ENUM ('MATHEMATICS','SCIENCE','THAI','SOCIAL_STUDIES','ENGLISH');
CREATE TYPE "Difficulty" AS ENUM ('BASIC','INTERMEDIATE','ADVANCED','COMPETITIVE','OLYMPIAD');
CREATE TYPE "QuestionType" AS ENUM ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','SHORT_ANSWER','NUMERIC_ANSWER');
CREATE TYPE "QuestionStatus" AS ENUM ('DRAFT','REVIEW','PUBLISHED','ARCHIVED','DELETED');
CREATE TYPE "AttemptStatus" AS ENUM ('IN_PROGRESS','SUBMITTED','EXPIRED','CANCELLED');
CREATE TYPE "RedeemStatus" AS ENUM ('ACTIVE','DISABLED');
CREATE TYPE "ThreadStatus" AS ENUM ('OPEN','LOCKED','ARCHIVED');
CREATE TYPE "ModerationStatus" AS ENUM ('VISIBLE','PENDING_REVIEW','HIDDEN','REMOVED');
CREATE TABLE "User" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"email" varchar(320) UNIQUE NOT NULL,"passwordHash" varchar(255),"displayName" varchar(120),"role" "UserRole" NOT NULL DEFAULT 'STUDENT',"status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',"points" integer NOT NULL DEFAULT 0,"level" integer NOT NULL DEFAULT 1,"sessionVersion" integer NOT NULL DEFAULT 1,"failedLoginCount" integer NOT NULL DEFAULT 0,"lockedUntil" timestamptz,"lastLoginAt" timestamptz,"subscriptionExpiresAt" timestamptz,"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now(),CHECK ("points">=0),CHECK ("level">0));
CREATE TABLE "Question" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"subject" "Subject" NOT NULL,"grade" integer NOT NULL,"difficulty" "Difficulty" NOT NULL,"type" "QuestionType" NOT NULL,"status" "QuestionStatus" NOT NULL DEFAULT 'DRAFT',"stem" text NOT NULL,"explanation" text,"correctAnswer" jsonb NOT NULL,"version" integer NOT NULL DEFAULT 1,"authorId" uuid,"fingerprint" varchar(64) NOT NULL,"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now(),"publishedAt" timestamptz,CHECK ("grade" BETWEEN 1 AND 12),CHECK ("version">0));
CREATE TABLE "QuestionChoice" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"questionId" uuid NOT NULL REFERENCES "Question"("id") ON DELETE CASCADE,"label" varchar(16) NOT NULL,"content" text NOT NULL,"isCorrect" boolean NOT NULL DEFAULT false,"sortOrder" integer NOT NULL,UNIQUE("questionId","sortOrder"));
CREATE TABLE "ExamAttempt" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"userId" uuid NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT,"subject" "Subject" NOT NULL,"mode" varchar(16) NOT NULL,"status" "AttemptStatus" NOT NULL DEFAULT 'IN_PROGRESS',"startedAt" timestamptz NOT NULL DEFAULT now(),"expiresAt" timestamptz,"submittedAt" timestamptz,"score" integer,"maxScore" integer,"percent" numeric(5,2),CHECK ("mode" IN ('PRACTICE','EXAM')));
CREATE TABLE "ExamAttemptQuestion" ("attemptId" uuid NOT NULL REFERENCES "ExamAttempt"("id") ON DELETE CASCADE,"questionId" uuid NOT NULL REFERENCES "Question"("id") ON DELETE RESTRICT,"questionVersion" integer NOT NULL,"sortOrder" integer NOT NULL,PRIMARY KEY("attemptId","questionId"),UNIQUE("attemptId","sortOrder"));
CREATE TABLE "AttemptAnswer" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"attemptId" uuid NOT NULL REFERENCES "ExamAttempt"("id") ON DELETE CASCADE,"questionId" uuid NOT NULL,"answer" jsonb NOT NULL,"clientRevision" integer NOT NULL DEFAULT 0,"isCorrect" boolean,"answeredAt" timestamptz NOT NULL DEFAULT now(),UNIQUE("attemptId","questionId"));
CREATE TABLE "RewardLedger" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"userId" uuid NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,"eventId" uuid UNIQUE NOT NULL,"sourceType" varchar(64) NOT NULL,"sourceId" varchar(100) NOT NULL,"reason" varchar(80) NOT NULL,"points" integer NOT NULL,"createdAt" timestamptz NOT NULL DEFAULT now(),UNIQUE("userId","sourceType","sourceId","reason"));
CREATE TABLE "RedeemCode" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"codeHash" varchar(64) UNIQUE NOT NULL,"status" "RedeemStatus" NOT NULL DEFAULT 'ACTIVE',"durationDays" integer NOT NULL,"maxUses" integer,"useCount" integer NOT NULL DEFAULT 0,"perUserLimit" integer NOT NULL DEFAULT 1,"validFrom" timestamptz NOT NULL,"validUntil" timestamptz NOT NULL,"planCode" varchar(80) NOT NULL,CHECK("durationDays">0),CHECK("useCount">=0),CHECK("perUserLimit">0),CHECK("validUntil">"validFrom"));
CREATE TABLE "RedeemRedemption" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"codeId" uuid NOT NULL REFERENCES "RedeemCode"("id") ON DELETE RESTRICT,"userId" uuid NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT,"requestId" uuid UNIQUE NOT NULL,"redeemedAt" timestamptz NOT NULL DEFAULT now(),"entitlementEndsAt" timestamptz NOT NULL);
CREATE TABLE "CommunityPost" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"authorId" uuid NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT,"board" varchar(80) NOT NULL,"title" varchar(240) NOT NULL,"body" text NOT NULL,"status" "ThreadStatus" NOT NULL DEFAULT 'OPEN',"moderationStatus" "ModerationStatus" NOT NULL DEFAULT 'VISIBLE',"pinned" boolean NOT NULL DEFAULT false,"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "AuditLog" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"actorId" uuid REFERENCES "User"("id") ON DELETE SET NULL,"action" varchar(120) NOT NULL,"resourceType" varchar(80) NOT NULL,"resourceId" varchar(100),"requestId" varchar(100) NOT NULL,"before" jsonb,"after" jsonb,"createdAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "ImportJob" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),"filename" varchar(255) NOT NULL,"mimeType" varchar(120) NOT NULL,"checksum" varchar(64) NOT NULL,"copyrightAttested" boolean NOT NULL,"status" varchar(40) NOT NULL,"createdById" uuid NOT NULL,"createdAt" timestamptz NOT NULL DEFAULT now());
CREATE INDEX "User_role_status_idx" ON "User"("role","status");
CREATE INDEX "Question_filter_idx" ON "Question"("subject","grade","difficulty","status");
CREATE INDEX "Question_publish_idx" ON "Question"("status","publishedAt");
CREATE INDEX "Question_fingerprint_idx" ON "Question"("fingerprint");
CREATE INDEX "Question_created_cursor_idx" ON "Question"("createdAt" DESC,"id");
CREATE INDEX "question_stem_trgm_idx" ON "Question" USING gin ("stem" gin_trgm_ops);
CREATE INDEX "ExamAttempt_history_idx" ON "ExamAttempt"("userId","startedAt" DESC);
CREATE INDEX "ExamAttempt_status_idx" ON "ExamAttempt"("userId","status");
CREATE INDEX "ExamAttempt_expiry_idx" ON "ExamAttempt"("status","expiresAt");
CREATE INDEX "RewardLedger_user_idx" ON "RewardLedger"("userId","createdAt" DESC);
CREATE INDEX "RedeemCode_status_idx" ON "RedeemCode"("status","validUntil");
CREATE INDEX "RedeemRedemption_user_idx" ON "RedeemRedemption"("userId","redeemedAt" DESC);
CREATE INDEX "CommunityPost_feed_idx" ON "CommunityPost"("board","moderationStatus","updatedAt" DESC);
CREATE INDEX "AuditLog_resource_idx" ON "AuditLog"("resourceType","resourceId","createdAt" DESC);
CREATE INDEX "ImportJob_status_idx" ON "ImportJob"("status","createdAt" DESC);
