import { randomUUID } from "node:crypto";
import type { Attempt,Difficulty,ExamMode,Question,RedeemCode,Role,Subject,User } from "./types";
import { Forbidden,hashPassword,hashSecret,requireRole,sameOwner,sanitizeText,verifyPassword } from "./security";
export class Platform {
  users=new Map<string,User>(); questions=new Map<string,Question>(); attempts=new Map<string,Attempt>(); codes=new Map<string,RedeemCode>(); redemptions=new Map<string,{expiresAt:number;codeHash:string}>(); rewards=new Set<string>(); posts=new Map<string,{id:string;authorId:string;body:string}>();
  register(email:string,password:string){if(this.findUser(email))throw new Error("EMAIL_EXISTS");const u:User={id:randomUUID(),email:email.toLowerCase(),passwordHash:hashPassword(password),role:"STUDENT",status:"ACTIVE",points:0,level:1};this.users.set(u.id,u);return u}
  provision(role:Role,email:string,password:string){const u=this.register(email,password);u.role=role;return u}
  login(email:string,password:string){const u=this.findUser(email);if(!u||u.status!=="ACTIVE"||!verifyPassword(password,u.passwordHash))throw new Error("INVALID_CREDENTIALS");return u}
  private findUser(email:string){return [...this.users.values()].find(u=>u.email===email.toLowerCase())}
  createQuestion(actor:User,input:{subject:Subject;grade:number;difficulty:Difficulty;stem:string;choices:string[];correct:number[];explanation:string}){requireRole(actor.role,["ADMIN","TEACHER"]);if(input.grade<1||input.grade>12)throw new Error("INVALID_GRADE");if(input.choices.length<2)throw new Error("INVALID_CHOICES");const q:Question={id:randomUUID(),subject:input.subject,grade:input.grade,difficulty:input.difficulty,stem:sanitizeText(input.stem),choices:input.choices.map((text,i)=>({id:`c${i}`,text:sanitizeText(text)})),correctChoiceIds:input.correct.map(i=>`c${i}`),explanation:sanitizeText(input.explanation),status:"REVIEW",version:1};this.questions.set(q.id,q);return q}
  publishQuestion(actor:User,id:string){requireRole(actor.role,["ADMIN"]);const q=this.questions.get(id);if(!q)throw new Error("NOT_FOUND");q.status="PUBLISHED";return q}
  importQuestions(actor:User,rows:Array<{stem:string;subject:Subject;grade:number;difficulty:Difficulty;choices:string[];correct:number[];explanation:string}>,copyrightAttested:boolean){requireRole(actor.role,["ADMIN"]);if(!copyrightAttested)throw new Error("COPYRIGHT_ATTESTATION_REQUIRED");return rows.map(r=>this.createQuestion(actor,r))}
  startExam(actor:User,subject:Subject,count:number,mode:ExamMode){requireRole(actor.role,["STUDENT"]);if(count<1||count>200)throw new Error("INVALID_COUNT");const qs=[...this.questions.values()].filter(q=>q.status==="PUBLISHED"&&q.subject===subject).slice(0,count);if(qs.length<count)throw new Error("INSUFFICIENT_INVENTORY");const a:Attempt={id:randomUUID(),userId:actor.id,questionIds:qs.map(q=>q.id),mode,answers:{},submitted:false,startedAt:Date.now()};this.attempts.set(a.id,a);return a}
  answer(actor:User,attemptId:string,questionId:string,choiceIds:string[]){const a=this.attempts.get(attemptId);if(!a)throw new Error("NOT_FOUND");sameOwner(actor.id,a.userId);if(a.submitted)throw new Error("ALREADY_SUBMITTED");if(!a.questionIds.includes(questionId))throw new Forbidden("QUESTION_NOT_IN_ATTEMPT");a.answers[questionId]=[...choiceIds];const q=this.questions.get(questionId)!;return a.mode==="PRACTICE"?{saved:true,correct:eqSet(choiceIds,q.correctChoiceIds)}:{saved:true}}
  submit(actor:User,attemptId:string){const a=this.attempts.get(attemptId);if(!a)throw new Error("NOT_FOUND");sameOwner(actor.id,a.userId);if(a.submitted)return {attempt:a,rewarded:false};let correct=0;for(const id of a.questionIds){const q=this.questions.get(id)!;if(eqSet(a.answers[id]||[],q.correctChoiceIds))correct++}a.submitted=true;a.score=correct;a.percent=Math.round(correct/a.questionIds.length*10000)/100;const rewardKey=`exam:${a.id}`;let rewarded=false;if(!this.rewards.has(rewardKey)){this.rewards.add(rewardKey);actor.points+=25+correct*10;rewarded=true}return {attempt:a,rewarded}}
  history(actor:User){return [...this.attempts.values()].filter(a=>a.userId===actor.id&&a.submitted)}
  tutor(actor:User,attemptId:string,questionId:string){const a=this.attempts.get(attemptId);if(!a)throw new Error("NOT_FOUND");sameOwner(actor.id,a.userId);if(!a.questionIds.includes(questionId))throw new Forbidden("QUESTION_NOT_IN_ATTEMPT");const q=this.questions.get(questionId)!;const student=a.answers[questionId]||[];const correct=eqSet(student,q.correctChoiceIds);return {correct,whyWrong:correct?null:"คำตอบไม่ตรงกับ answer key ที่ตรวจสอบแล้ว",concept:q.explanation,hint:`ทบทวนแนวคิดของ ${q.subject}`,practice:`โจทย์ฝึกเพิ่มเติมระดับ ${q.difficulty}`}}
  createRedeemCode(actor:User,raw:string,durationDays:number,maxUses:number,perUserLimit=1){requireRole(actor.role,["ADMIN"]);const now=Date.now();const c:RedeemCode={id:randomUUID(),hash:hashSecret(raw),durationDays,maxUses,uses:0,perUserLimit,active:true,validFrom:now-1000,validUntil:now+365*86400000};this.codes.set(c.hash,c);return c}
  redeem(actor:User,raw:string,requestId:string){requireRole(actor.role,["STUDENT"]);const idempotency=`${actor.id}:${requestId}`;if(this.redemptions.has(idempotency))return {expiresAt:this.redemptions.get(idempotency)!.expiresAt,idempotent:true};const c=this.codes.get(hashSecret(raw));const now=Date.now();if(!c||!c.active||now<c.validFrom||now>c.validUntil||c.uses>=c.maxUses)throw new Error("INVALID_CODE");const previous=[...this.redemptions.entries()].filter(([k,v])=>k.startsWith(actor.id+":")&&v.codeHash===c.hash);if(previous.length>=c.perUserLimit)throw new Error("PER_USER_LIMIT");const base=Math.max(now,actor.subscriptionExpiresAt||0);const expiry=base+c.durationDays*86400000;c.uses++;actor.subscriptionExpiresAt=expiry;this.redemptions.set(idempotency,{expiresAt:expiry,codeHash:c.hash});return {expiresAt:expiry,idempotent:false}}
  createPost(actor:User,body:string){if(actor.status!=="ACTIVE")throw new Forbidden("SUSPENDED");const p={id:randomUUID(),authorId:actor.id,body:sanitizeText(body)};this.posts.set(p.id,p);return p}
  editPost(actor:User,id:string,body:string){const p=this.posts.get(id);if(!p)throw new Error("NOT_FOUND");sameOwner(actor.id,p.authorId);p.body=sanitizeText(body);return p}
}
function eqSet(a:string[],b:string[]){return a.length===b.length&&[...a].sort().every((x,i)=>x===[...b].sort()[i])}
